version: 0.1.0.{branch}.{build}

environment:
  matrix:
  # MinGW Static
  - name: win32_static
    platform: mingw
    qt: static\5.7.1\mingw53_32
    suffix: mingw_x86

  # MinGW
  - name: win32
    platform: mingw
    qt: 5.7\mingw53_32
    suffix: mingw_x86

  # MSVC x86
  - name: win32
    platform: x86
    qt: 5.7\msvc2015
    suffix: msvc2015_x86

  # MSVC x64
  - name: win64
    platform: amd64
    qt: 5.7\msvc2015_64
    suffix: msvc2015_x64

init:
  - if %platform%==mingw set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if %platform%==mingw set PATH=C:\Qt\Tools\mingw530_32\bin;%PATH%
  - set PATH=C:\Qt\%qt%\bin;%PATH%
  - if not %platform%==mingw call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %platform%
  - if not %platform%==mingw (set spec=win32-msvc2015) else (set spec=win32-g++)
  - if not %platform%==mingw set PATH=C:\Qt\Tools\QtCreator\bin;%PATH%
  - if %name%==win32_static curl -fsS -o qt-static-mingw53_32-5.7.1.7z https://drive.google.com/uc?export=download&confirm=nOBt&id=0B72hTjcCv9EAYWgyUVUwVTVKbFE
  - if %name%==win32_static 7z x qt-static-mingw53_32-5.7.1.7z -oC:\Qt\static

before_build:
  - md build-%suffix%

build_script:
  - cd build-%suffix%
  - qmake ..\redshiftqt\RedShiftQt.pro -spec %spec%
  - if not %platform%==mingw (jom) else (mingw32-make)
  
artifacts:
- path: build-%suffix%\release\RedShiftQt.exe