os: linux
dist: trusty
language: cpp

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt571-trusty
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt57base
  - source /opt/qt57/bin/qt57-env.sh

script:
  - mkdir build
  - cd build
  - qmake ../redshiftqt/RedShiftQt.pro
  - make